### ISSUE TITLE
wooify fails with django 1.9

### ISSUE THREAD

**Issue by yoavram** [wooey/Wooey#101] opened 2016-01-02 13:32 UTC
Installing latest wooey on Python 3.4.3 on Win7 65bit, without previous install of django, installed django 1.9.
Running `wooify -p test` caused this error:
```
λ wooify --version
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\wooify.exe\__main__.py", line 5, in <module>
  File "d:\anaconda3\lib\site-packages\wooey\backend\command_line.py", line 8, in <module>
    from .. import django_compat
  File "d:\anaconda3\lib\site-packages\wooey\django_compat.py", line 51, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
  File "d:\anaconda3\lib\site-packages\django\contrib\contenttypes\fields.py", line 5, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "d:\anaconda3\lib\site-packages\django\contrib\contenttypes\models.py", line 159, in <module>
    class ContentType(models.Model):
  File "d:\anaconda3\lib\site-packages\django\db\models\base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "d:\anaconda3\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "d:\anaconda3\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
Installing django 1.8 (`pip install django==1.8`) fixed it (albeit giving a different error, I'll look into it and open a different issue if needed).

**Comment by Chris7** [comment] 2016-01-02 14:38
Thanks @yoavram for the report. It looks like it's because we import GFK from a place that has moved in DJ1.9.I'll look into fixing it.

**Comment by Chris7** [comment] 2016-01-02 15:07
It appears the GFK framework has changed a bit that is interfering with the bootstrapping process. I think it's trying to load the modules during the bootstrap which is causing the Apps aren't loaded yet error.

**Comment by Chris7** [comment] 2016-01-02 15:20
ticket created here: https://code.djangoproject.com/ticket/26023#ticket

**Comment by PierreBourgault** [comment] 2016-01-06 19:27
I just saw that the ticket has been closed as invalid. I don't undertand why it is being closed since the issue is still there. I just installed wooey with pip install wooey (python 2.7, 32-bits) and then followed the instructions at http://wooey.readthedocs.org/en/latest/install.html#a-wooey-only-project to install wooey without an existing django and it does not work. Please fix the problem or else fix the instructions. Best regards.

**Comment by Chris7** [comment] 2016-01-06 19:31
I'm not the person who closed it as invalid on Django. I also don't feel like expending the energy to convince them to fix it as opposed to just make a workaround in Wooey. 

This is fixed in the version of Wooey on github, which may be installed via

pip install git+https://github.com/wooey/Wooey.git

We are currently going over which milestones we want to incorporate for the next release of Wooey, and haven't evaluated what should go into a quick-fix for pypi. That should be resolved shortly.

**Comment by PierreBourgault** [comment] 2016-01-06 19:35
ok thanks.

**Comment by PierreBourgault** [comment] 2016-01-06 20:09
So, I was able to install gooey with pip install git+https://github.com/wooey/Wooey.git.

However, the wooify -p test command still fails, this time with a different error:

ImportError: No module named django
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> c:\python27\lib\importlib\__init__.py(37)import_module()
-> __import__(name)
(Pdb) where
  c:\python27\lib\pdb.py(1314)main()
-> pdb._runscript(mainpyfile)
  c:\python27\lib\pdb.py(1233)_runscript()
-> self.run(statement)
  c:\python27\lib\bdb.py(400)run()
-> exec cmd in globals, locals
  <string>(1)<module>()
  d:\dev\pyhub\manage.py(2)<module>()
-> import os
  c:\python27\lib\site-packages\django\core\management\__init__.py(353)execute_from_command_line()
-> utility.execute()
  c:\python27\lib\site-packages\django\core\management\__init__.py(327)execute()
-> django.setup()
  c:\python27\lib\site-packages\django\__init__.py(18)setup()
-> apps.populate(settings.INSTALLED_APPS)
  c:\python27\lib\site-packages\django\apps\registry.py(85)populate()
-> app_config = AppConfig.create(entry)
  c:\python27\lib\site-packages\django\apps\config.py(123)create()
-> import_module(entry)
> c:\python27\lib\importlib\__init__.py(37)import_module()
-> __import__(name)
(Pdb) up
> c:\python27\lib\site-packages\django\apps\config.py(123)create()
-> import_module(entry)
(Pdb) p entry
'kombu.transport.django'
(Pdb) import kombu.transport.django
*** ImportError: No module named django

**Comment by Chris7** [comment] 2016-01-06 20:16
Yes, that's actually another bug related to kombu. Their latest release to
pypi is broken and you'll need to use kombu==3.0.31 until they fix it.

**Comment by PierreBourgault** [comment] 2016-01-06 20:20
I see. So I did pip install kombu==3.0.31 and it did remove the error. But then, I stumbled on the next one:

D:\dev\pyhub>python manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 52, in execute
    return super(Command, self).execute(*args, **options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 86, in handle
    default_username = get_default_username()
  File "C:\Python27\lib\site-packages\django\contrib\auth\management\__init__.py", line 189, in get_default_username
    auth_app.User._default_manager.get(username=default_username)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 381, in get
    num = len(clone)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 240, in __len__
    self._fetch_all()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "C:\Python27\lib\site-packages\django\db\models\sql\compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python27\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django\db\backends\sqlite3\base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user

**Comment by Chris7** [comment] 2016-01-06 20:46
That's because the bootstrapping failed. If you are in the project that you previously had an error on, rerun wooify or setup your database. The error is because you have not applied migrations and thus the tables django needs are not present. Sorry to be brief, but I'm on my phone right now.

**Comment by PierreBourgault** [comment] 2016-01-06 20:49
Awesome !! It works now. Big thanks for your quick replies !

**Comment by PierreBourgault** [comment] 2016-01-06 20:51
Well, the server start but as soon I hit the URL (localhost:800) i got an internal server error: 
D:\dev\pyhub>python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
January 06, 2016 - 15:49:05
Django version 1.9.1, using settings 'pyhub.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 172, in get_response
    response = response.render()
  File "C:\Python27\lib\site-packages\django\template\response.py", line 160, in render
    self.content = self.rendered_content
  File "C:\Python27\lib\site-packages\django\template\response.py", line 135, in rendered_content
    template = self._resolve_template(self.template_name)
  File "C:\Python27\lib\site-packages\django\template\response.py", line 90, in _resolve_template
    new_template = self.resolve_template(template)
  File "C:\Python27\lib\site-packages\django\template\response.py", line 80, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 62, in select_template
    return engine.get_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\backends\django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "C:\Python27\lib\site-packages\django\template\engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Python27\lib\site-packages\django\template\loaders\base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Python27\lib\site-packages\django\template\base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 514, in parse
    raise self.error(token, e)
TypeError: __init__() takes exactly 5 arguments (4 given)

**Comment by fritchie** [comment] 2016-01-06 23:04
I received the same error as Pierre

**Comment by Chris7** [comment] 2016-01-07 14:35
Could you elaborate more on your environment? What version of python? What is the output of pip freeze?

**Comment by PierreBourgault** [comment] 2016-01-07 15:22
Python version: Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Output of pip freeze: 
amqp==1.4.8
anyjson==0.3.3
billiard==3.3.0.22
celery==3.1.19
clinto==0.1.2
Django==1.9.1
django-autoslug==1.9.3
django-celery==3.1.17
docx==0.2.4
Gooey==0.8.16
graphviz==0.4.7
kombu==3.0.31
lxml==3.4.4
onepy==0.2.1
Pillow==3.0.0
pyad==0.5.14
pyodbc==3.0.7
pyperclip==1.5.16
python-docx==0.8.5
pytz==2015.7
pywin32==219
six==1.10.0
snakefood==1.4
wooey==0.9.1
xerox==0.3.1

**Comment by oinbar** [comment] 2016-01-20 17:19
I am trying to create a new project with wooify -p ProjectName, and also getting the 
"django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet." error.

I am new to django. Is there a previous version of wooey I can use?

**Comment by Chris7** [comment] 2016-01-20 17:37
You can install Django 1.8 with:
pip install Django==1.8

In a few days I'll release the next version that resolves this problem. This update also resolves your error @PierreBourgault and @fritchie.

If you want it now, you can install the development branch of wooey with:
pip install git+https://www.github.com/wooey/wooey

**Comment by oinbar** [comment] 2016-01-20 18:02
Wonderful, it works from the repo version. This seems like a great project! exactly what I needed.

**Comment by PierreBourgault** [comment] 2016-01-20 19:23
Great ! Tried it and it does work fine now ! Many thanks.

**Closed** 2016-02-01 03:46 UTC
