### ISSUE TITLE
OperationalError: no such column: wooey_script.documentation

### ISSUE THREAD

**Issue by CatherineH** [wooey/Wooey#99] opened 2015-11-27 16:29 UTC
I recently updated Wooey from 0.2.6 to 0.9.1, and now I get the error:

```
django.db.backends.sqlite3.base in execute
OperationalError: no such column: wooey_script.documentation
```

on the file wooey/views/views.py on line 237: 
```
            return self.search(request, *args, **kwargs)
```
Is there an documented method for updating wooey?

**Comment by Chris7** [comment] 2015-11-27 17:00
Run ./manage.py migrate wooey

**Comment by CatherineH** [comment] 2015-11-27 17:23
I'm getting this error:

```
django.db.utils.IntegrityError: NOT NULL constraint failed: wooey_wooeyjob__new.script_version_id
```

**Comment by Chris7** [comment] 2015-11-27 17:28
Oh, Wooey 0.2.6 I think is Flask based. Wooey is now run on Django. I don't think there is an upgrade path from Flask to Django that is documented. You could export the data though and re-import it to a Django database I suppose (though it might involve a little bit of hacking)

**Comment by Chris7** [comment] 2015-11-27 17:31
I'm mistaken on that. 0.2.6 was a Django release. Did you install from github though, or was that installed from pypi?

**Comment by CatherineH** [comment] 2015-11-27 17:33
From pypi.

**Comment by Chris7** [comment] 2015-11-28 04:07
Could you paste your list of migrations applied?

**Comment by CatherineH** [comment] 2015-11-30 15:04
Sorry, I just removed everything and re-built the project  with Wooey 0.9.1, so I'm not sure I can get you that information now.

**Comment by Chris7** [comment] 2015-11-30 16:10
Thanks @CatherineH for the report in any case. If you happen to have the database around too, you could email/post that to me and I can take a look. If you are using the sqlite3 backend, that may be the cause -- I've found quite a few unexplained errors due to some features sqlite3 lacks and using something like PostgreSQL is much more robust.

**Comment by Chris7** [comment] 2015-12-02 16:28
Closing this as it seems it's been fixed.

**Closed by Chris7** 2015-12-02 16:28 UTC
